# Project Overview
- For this project, you will use data cleaning, imputation, analysis, and visualization to generate insights for a business stakeholder.
# Business Problem
- Your company is expanding in to new industries to diversify its portfolio. Specifically, they are interested in purchasing and operating airplanes for commercial and private enterprises, but do not know anything about the potential risks of aircraft. You are charged with determining which aircraft are the lowest risk for the company to start this new business endeavor. You must then translate your findings into actionable insights that the head of the new aviation division can use to help decide which aircraft to purchase.

In [ ]:
import numpy as np 
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.cm as cm

In [2]:
# Reading csv files

Aviation = pd.read_csv("Airplane_Crashes_and_Fatalities_Since_1908_20190820105639.csv", encoding= 'latin-1')

In [3]:
# Checking the head of data
Aviation.head()

,Date,Time,Location,Operator,Flight #,Route,AC Type,Registration,cn/ln,Aboard,Aboard Passangers,Aboard Crew,Fatalities,Fatalities Passangers,Fatalities Crew,Ground,Summary
0,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,2.0,1.0,1.0,1.0,1.0,0.0,0.0,"During a demonstration flight, a U.S. Army fly..."
1,09/07/1909,NaN,"Juvisy-sur-Orge, France",NaN,NaN,Air show,Wright Byplane,SC1,NaN,1.0,0.0,1.0,1.0,0.0,0.0,0.0,Eugene Lefebvre was the first pilot to ever be...
2,07/12/1912,06:30,"Atlantic City, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,5.0,0.0,5.0,5.0,0.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...
3,08/06/1913,NaN,"Victoria, British Columbia, Canada",Private,NaN,NaN,Curtiss seaplane,NaN,NaN,1.0,0.0,1.0,1.0,0.0,1.0,0.0,The first fatal airplane accident in Canada oc...
4,09/09/1913,18:30,Over the North Sea,Military - German Navy,NaN,NaN,Zeppelin L-1 (airship),NaN,NaN,20.0,NaN,NaN,14.0,NaN,NaN,0.0,The airship flew into a thunderstorm and encou...

In [4]:
# Checking the tail of data
Aviation.tail()

,Date,Time,Location,Operator,Flight #,Route,AC Type,Registration,cn/ln,Aboard,Aboard Passangers,Aboard Crew,Fatalities,Fatalities Passangers,Fatalities Crew,Ground,Summary
4962,04/16/2019,11:00,"Puerto Montt, Chile",Archipelagos Service Aereos,NaN,Puerto Montt - Ayacara,Pilatus-Britten Norman BN-2B-27 Islander,CC-CYRÂ,2169,6.0,5.0,1.0,6.0,5.0,1.0,0.0,"While the aircraft was in the initial climb, p..."
4963,05/05/2019,18:30,"Near Monclava, Mexico",TVPX Aircraft Solutions,NaN,Las Vegas - Monterrey,Canadair CL-600-2B16-Challenger,N601VH,5043,13.0,11.0,2.0,13.0,11.0,2.0,0.0,The aircraft crashed while en route on a retur...
4964,05/05/2019,18:30,"Moscow, Russia",Aeroflot Russian International Airlines,NaN,Moscow - Murmansk,Sukhoi Superjet-100-95B,RA-89098Â,95135,78.0,73.0,5.0,41.0,40.0,1.0,0.0,Forty-five minutes after taking off from Mosco...
4965,06/03/2019,13:00,"Near Lipo, India",Military - Indian Air Force,NaN,Jorhat-Rowriah - Mechuka,Antonov An-32,K2752,1009,13.0,5.0,8.0,13.0,5.0,8.0,0.0,Crashed about 34km WNW of Mechuka.
4966,07/30/2019,02:00,"Rawalpindi, India",Military - Pakistan Army,NaN,Training,Beechcraft B300 King Air,766,B766,5.0,0.0,5.0,5.0,0.0,5.0,14.0,"The Pakistani military plane, on a training fl..."

In [5]:
# List of data's columns
Aviation.columns

Index(['Date', 'Time', 'Location', 'Operator', 'Flight #', 'Route', 'AC Type',
       'Registration', 'cn/ln', 'Aboard', 'Aboard Passangers', 'Aboard Crew',
       'Fatalities', 'Fatalities Passangers', 'Fatalities Crew', 'Ground',
       'Summary'],
      dtype='object')

In [6]:
# Summary statistics of numeric columns
Aviation.describe()

,Aboard,Aboard Passangers,Aboard Crew,Fatalities,Fatalities Passangers,Fatalities Crew,Ground
count,4949.000000,4738.000000,4741.000000,4959.000000,4725.000000,4726.000000,4926.000000
mean,31.088301,26.898691,4.479646,22.338173,19.017566,3.579348,1.728177
std,45.438282,44.010591,3.489021,35.026176,34.114849,3.170223,55.708966
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.000000,3.000000,2.000000,4.000000,1.000000,2.000000,0.000000
50%,16.000000,12.000000,4.000000,11.000000,8.000000,3.000000,0.000000
75%,35.000000,30.000000,6.000000,25.000000,21.000000,5.000000,0.000000
max,644.000000,614.000000,61.000000,583.000000,560.000000,46.000000,2750.000000

# Data cleaning and Data Handling

In [7]:
# data information
Aviation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4967 entries, 0 to 4966
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   4967 non-null   object
 1   Time                   3457 non-null   object
 2   Location               4963 non-null   object
 3   Operator               4957 non-null   object
 4   Flight #               1315 non-null   object
 5   Route                  4192 non-null   object
 6   AC Type                4952 non-null   object
 7   Registration           4694 non-null   object
 8   cn/ln                  4299 non-null   object
 9   Aboard                 4949 non-null   float64
 10  Aboard Passangers      4738 non-null   float64
 11  Aboard Crew            4741 non-null   float64
 12  Fatalities             4959 non-null   float64
 13  Fatalities Passangers  4725 non-null   float64
 14  Fatalities Crew        4726 non-null   float64
 15  Ground                 4926 non-null   float64
 16  Summary                4903 non-null   object
dtypes: float64(7), object(10)
memory usage: 659.8+ KB

In [ ]:
# checking for null values
Aviation.isna().sum()/len(Aviation)*100

In [62]:
# I am going to drop columns that have roughly more than 25% of their data missing
columns_to_drop = ['Latitude', 'Longitude', 'Airport.Code', 'Airport.Name', 'Aircraft.Category', 'FAR.Description',
                   'Schedule', 'Air.carrier', 'Broad.phase.of.flight']

df_clean = Aviation.drop(columns=columns_to_drop)

In [63]:
#I think there are many columns which are not important for my analysis. I drop these columns for easier handling of data 
# and clearer analysis
more_columns_to_drop = ['Accident.Number', 'Registration.Number', 'Amateur.Built', 
                   'Publication.Date', 'Publication.Date', 'Report.Status','Engine.Type']
df_clean = df_clean.drop(columns=more_columns_to_drop)

In [64]:
df_clean.columns

Index(['Event.Id', 'Investigation.Type', 'Event.Date', 'Location', 'Country',
       'Injury.Severity', 'Aircraft.damage', 'Make', 'Model',
       'Number.of.Engines', 'Purpose.of.flight', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition'],
      dtype='object')

In [65]:
# I change some column titles to more managable ones
new_column_names = {'vent.Id': 'ID', 'Investigation.Type': 'Type', 'Event.Date':'Date', 'Injury.Severity':'Injury_Severity', 
                    'Aircraft.damage':'Damage_type', 'Number.of.Engines':'Engines', 'Purpose.of.flight':'Flight_Purpose',
                    'Total.Fatal.Injuries':'Fatal_Injuries', 'Total.Serious.Injuries':'Serious_Injuries',
                   'Total.Minor.Injuries':'Minor_Injuries', 'Total.Uninjured':'Uninjured', 'Weather.Condition':'Weather',}
df_clean.rename(columns=new_column_names, inplace=True)

In [66]:
df_clean.head()

,Event.Id,Type,Date,Location,Country,Injury_Severity,Damage_type,Make,Model,Engines,Flight_Purpose,Fatal_Injuries,Serious_Injuries,Minor_Injuries,Uninjured,Weather
0,20001218X45444,Accident,1948-10-24,"MOOSE CREEK, ID",United States,Fatal(2),Destroyed,Stinson,108-3,1.0,Personal,2.0,0.0,0.0,0.0,UNK
1,20001218X45447,Accident,1962-07-19,"BRIDGEPORT, CA",United States,Fatal(4),Destroyed,Piper,PA24-180,1.0,Personal,4.0,0.0,0.0,0.0,UNK
2,20061025X01555,Accident,1974-08-30,"Saltville, VA",United States,Fatal(3),Destroyed,Cessna,172M,1.0,Personal,3.0,NaN,NaN,NaN,IMC
3,20001218X45448,Accident,1977-06-19,"EUREKA, CA",United States,Fatal(2),Destroyed,Rockwell,112,1.0,Personal,2.0,0.0,0.0,0.0,IMC
4,20041105X01764,Accident,1979-08-02,"Canton, OH",United States,Fatal(1),Destroyed,Cessna,501,NaN,Personal,1.0,2.0,NaN,0.0,VMC

- While exploring the data above it came to my attention that columns 'Injury.Severity' and 'Total.Fatal.Injuries' provide similar information but 'Total.Fatal.Injuries' has many missing data. By extracting data from these two columns, I create a new Fatality column with less missing numerical data than 'Total.Fatal.Injuries'

In [67]:
df_clean['Fatality'] = df_clean['Injury_Severity'].str.extract(r'\((\d+)\)')
df_clean['Fatality'].fillna(df_clean['Injury_Severity'], inplace=True)
df_clean['Fatality'].replace({'Non-Fatal': 0, 'Minor': 0, 'Serious': 0, 'Incident': 0}, inplace=True)
df_clean['Fatality'] = df_clean.apply(lambda row: row['Fatal_Injuries'] if row['Fatality'] == 'Fatal' else row['Fatality'], axis=1)
df_clean['Fatality'].replace('Unavailable', np.nan, inplace=True)
df_clean['Fatality'][~df_clean['Fatality'].isna()] = df_clean['Fatality'][~df_clean['Fatality'].isna()].astype(int)
pd.options.display.float_format = '{:.0f}'.format

C:\Users\DELL\AppData\Local\Temp\ipykernel_3968\1541478884.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['Fatality'].fillna(df_clean['Injury_Severity'], inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_3968\1541478884.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean['Fatality'].replace('Unavailable', np.nan, inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_3968\1541478884.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_clean['Fatality'][~df_clean['Fatality'].isna()] = df_clean['Fatality'][~df_clean['Fatality'].isna()].astype(int)
C:\Users\DELL\AppData\Local\Temp\ipykernel_3968\1541478884.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clean['Fatality'][~df_clean['Fatality'].isna()] = df_clean['Fatality'][~df_clean['Fatality'].isna()].astype(int)

In [68]:
# My Fatality column with more accurate representation of Fatality counts has been created 
df_clean['Fatality'].value_counts()

Fatality
0      69998
1       8867
2       5172
3       1588
4       1103
       ...
66         1
112        1
188        1
41         1
176        1
Name: count, Length: 125, dtype: int64

In [69]:
# We can drop Fatal_injuries column now
df_clean.drop(columns=['Fatal_Injuries'], inplace=True)

In [70]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Event.Id          88889 non-null  object
 1   Type              88889 non-null  object
 2   Date              88889 non-null  object
 3   Location          88837 non-null  object
 4   Country           88663 non-null  object
 5   Injury_Severity   87889 non-null  object
 6   Damage_type       85695 non-null  object
 7   Make              88826 non-null  object
 8   Model             88797 non-null  object
 9   Engines           82805 non-null  float64
 10  Flight_Purpose    82697 non-null  object
 11  Serious_Injuries  76379 non-null  float64
 12  Minor_Injuries    76956 non-null  float64
 13  Uninjured         82977 non-null  float64
 14  Weather           84397 non-null  object
 15  Fatality          87793 non-null  object
dtypes: float64(4), object(12)
memory usage: 10.9+ MB

In [71]:
# changing date type to the appropriate format and creating a column for seasons
df_clean['Date'] = pd.to_datetime(df_clean['Date'], format='%Y-%m-%d')
df_clean['Month'] = df_clean['Date'].dt.month
seasons = {
    12: 'Winter', 1: 'Winter', 2: 'Winter',
    3: 'Spring', 4: 'Spring', 5: 'Spring',
    6: 'Summer', 7: 'Summer', 8: 'Summer',
    9: 'Fall', 10: 'Fall', 11: 'Fall'
}

df_clean['Season'] = df_clean['Month'].map(seasons)

In [72]:
# I am going to create more new columns out of Date columns for future analysis and visualisations
df_clean['Year'] = df_clean['Date'].dt.year

In [73]:
# While exploring the dataframe, I realised United States is overrepresented in Country column
# more than 90% of the Country column is the United States. As I wanted to focus on the US aviation accidents
# I create a new dataframe df_us to focus on the United States
df_clean['Country'].value_counts()

Country
United States               82248
Brazil                        374
Canada                        359
Mexico                        358
United Kingdom                344
                            ...
Mauritania                      1
Pacific Ocean                   1
Obyan                           1
Guernsey                        1
Turks and Caicos Islands        1
Name: count, Length: 219, dtype: int64

In [74]:
df_us = df_us = df_clean[df_clean['Country'] == 'United States']
df_us.reset_index(drop=True, inplace=True)

In [75]:
# I create new columns using Location for future geographical analysis and visualisations. 
#This was easier on Jupyter notebook by pip install us & import us, but it did not work on Kaggle
# So I ended up creating a list of valid US states codes

valid_state_codes = [
    'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 
    'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 
    'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 
    'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 
    'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'
]
def extract_city_state(location):
    if pd.notna(location):
        location = location.strip()
        last_two_chars = location[-2:].upper()
        if last_two_chars in valid_state_codes:
            return location[:-3].strip(), last_two_chars
        else:
            return location, "Not Applicable" # Some accidents have not happend in a particular state
    else:
        return np.nan, np.nan

df_us[['City', 'State']] = df_us['Location'].apply(extract_city_state).apply(pd.Series)

C:\Users\DELL\AppData\Local\Temp\ipykernel_3968\1154728101.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_us[['City', 'State']] = df_us['Location'].apply(extract_city_state).apply(pd.Series)
C:\Users\DELL\AppData\Local\Temp\ipykernel_3968\1154728101.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_us[['City', 'State']] = df_us['Location'].apply(extract_city_state).apply(pd.Series)

In [76]:
# getting rid of trailing commas in City column
df_us['City'] = df_us['City'].str.rstrip(',')

C:\Users\DELL\AppData\Local\Temp\ipykernel_3968\4057110884.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_us['City'] = df_us['City'].str.rstrip(',')

In [77]:
# having devided Location and Date columns, now we can drop these as well
df_us.drop(columns=['Date', 'Location'], inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_3968\3023645590.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_us.drop(columns=['Date', 'Location'], inplace=True)

In [78]:
# I noticed Fatality column has somehow returned to object type (not sure why?) so I change it to numeric again
df_us['Fatality'] = pd.to_numeric(df_us['Fatality'], errors='coerce')

C:\Users\DELL\AppData\Local\Temp\ipykernel_3968\1470701381.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_us['Fatality'] = pd.to_numeric(df_us['Fatality'], errors='coerce')

In [79]:
# Now my dataframe is ready for further analysis. There are still some missing data but I believe this is not 
# significant to impact my analysis
df_us.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82248 entries, 0 to 82247
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Event.Id          82248 non-null  object
 1   Type              82248 non-null  object
 2   Country           82248 non-null  object
 3   Injury_Severity   82140 non-null  object
 4   Damage_type       80269 non-null  object
 5   Make              82227 non-null  object
 6   Model             82210 non-null  object
 7   Engines           80373 non-null  float64
 8   Flight_Purpose    79819 non-null  object
 9   Serious_Injuries  70873 non-null  float64
 10  Minor_Injuries    71519 non-null  float64
 11  Uninjured         77243 non-null  float64
 12  Weather           81603 non-null  object
 13  Fatality          82125 non-null  float64
 14  Month             82248 non-null  int32
 15  Season            82248 non-null  object
 16  Year              82248 non-null  int32
 17  City              82237 non-null  object
 18  State             82237 non-null  object
dtypes: float64(5), int32(2), object(12)
memory usage: 11.3+ MB

In [92]:
# Export cleaned data to a new Excel file
cleaned_file_path = 'cleaned_aviation_data.xlsx'
df_us.to_excel(cleaned_file_path, index=False)